name: percent_indicator
description: Updated for Flutter dart null safety. Library that allows you to display progress widgets based on percentage, can be Circular or Linear, you can also customize it to your needs.
version: 3.0.0-nullsafety.9001
homepage: https://github.com/COVIDSafePlace/flutter_percent_indicator/
repository: https://github.com/COVIDSafePlace/flutter_percent_indicator/

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
